name: menzy
description: A new Flutter project.

publish_to: 'none'


version: 1.0.1+2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.3
  shared_preferences: ^2.0.12
  fluttertoast: ^8.0.9
  permission_handler: ^10.2.0
  syncfusion_flutter_gauges: ^20.2.36
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.1.1
  location: ^4.4.0
  geolocator: ^9.0.2
  flutter_polyline_points: ^1.0.0
  pedometer: ^3.0.0
  lottie: ^1.2.1
  flutter_rating_bar: ^4.0.0
  floor: ^1.2.0
  path_provider: ^2.0.8
  solid_bottom_sheet: ^0.1.10
  date_picker_timeline: ^1.2.3
  fl_chart: ^0.55.0
  stop_watch_timer: ^1.3.1
  date_format: ^2.0.5
#  flutter_local_notifications: ^9.9.1
  flutter_native_timezone: ^2.0.0
  charts_flutter: ^0.12.0
  share_plus: ^4.0.10
  url_launcher: ^6.1.5
  auto_size_text: ^3.0.0
  rate_my_app: ^1.1.1+1
  # google_mobile_ads: ^1.0.1
  app_tracking_transparency: ^2.0.2+1
  get: ^4.6.5
  image_picker: ^0.8.5+3
  video_box: ^0.16.1
  dio: ^4.0.6
  video_compress: ^3.1.1
  file_selector: ^0.8.4+3
  font_awesome_flutter: ^10.1.0
  google_sign_in: ^5.3.3
  flutter_svg: ^1.1.1+1
  camera: ^0.9.8+1
  video_player: ^2.4.5
  percent_indicator: ^4.2.2
  flutter_background_service: ^2.1.3
  device_info_plus: ^4.0.0
  screenshot: ^1.2.3
  flutter_easyloading: ^3.0.5
  cron: ^0.5.0
  # path_provider: ^2.0.11
  fluttermoji: ^1.0.0
  walletconnect_dart: ^0.0.10
  web3dart: ^2.3.5
  cached_network_image: ^3.2.1
  firebase_auth: ^4.1.1
  firebase_core: ^2.1.1
  http: ^0.13.4
  syncfusion_flutter_sliders: ^20.2.40 
  appcheck: ^1.0.5
  store_redirect: ^2.0.1
  image_gallery_saver: ^1.7.1
  intl: ^0.17.0
  flutter_launcher_icons: ^0.10.0
  firebase_crashlytics: ^3.0.4
  slider_button: ^2.0.0
  flutter_phoenix: ^1.0.0
  awesome_dialog: ^2.2.1
  pin_code_text_field: ^1.8.0
  ethers: ^0.0.1+3
  introduction_screen: ^3.0.2
  modal_bottom_sheet: ^2.1.2
  firebase_dynamic_links: ^5.0.4
  change_app_package_name: ^1.1.0
  cloud_firestore: ^4.0.4
  avatar_glow: ^2.0.2
  connectivity_plus: ^2.3.9
  internet_connection_checker: ^1.0.0+1
  firebase_messaging: ^14.0.4
  showcaseview: ^1.1.8
  flutter_unity_widget:
#      path: "/Users/macmini/Downloads/flutter-unity-view-widget-master"
  flutter_video_info:
      path: "alteredpkg/flutter_video_info-master"


dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.2.0
  build_runner: ^2.1.5
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 600
        - asset: fonts/Roboto-Black.ttf
          weight: 700



  uses-material-design: true

  assets:
   - assets/
   - assets/icons/
   - assets/images/
   - assets/map_styles/



