// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCer4VUl5F2ORA1xjQbFq5q_pRyiirjfcc',
    appId: '1:391837352163:android:070b2132b0df7c0a1a05d6',
    messagingSenderId: '391837352163',
    projectId: 'menzyapp-368b0',
    storageBucket: 'menzyapp-368b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk4PvjCK0HnOBgKMWfjw-is_jPPF-Ek9s',
    appId: '1:391837352163:ios:324263ef6b0a9cb41a05d6',
    messagingSenderId: '391837352163',
    projectId: 'menzyapp-368b0',
    storageBucket: 'menzyapp-368b0.appspot.com',
    androidClientId: '391837352163-9om15d0h2bt6o1chs9equl4albuifs6s.apps.googleusercontent.com',
    iosClientId: '391837352163-s43hl8j24e5gcm6r3re5274sd3qevih8.apps.googleusercontent.com',
    iosBundleId: 'com.steptracker.waterreminder.maprunner',
  );
}
